version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.4
      environment:
        PIPENV_VENV_IN_PROJECT: true

    branches:
      only:
        - master

    steps:
    - checkout
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

    - run:
        command: ls /home/circleci/project/


    - restore_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

    - run:
        name: install dependencies
        command: |
          sudo pip install pipenv
          pipenv install

    - save_cache:
        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
        paths:
          - ".venv"
          - "/usr/local/bin"
          - "/usr/local/lib/python3.6/site-packages"

    - run:
        name: check
        command: pipenv run python manage.py test

    - run:
        name: heroku deploy
        command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master