version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
    - checkout

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

    - save_cache:
        paths:
          - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}


    - run:
        name: check
        command: python3 manage.py check