version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.4
      environment:
        PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
    - checkout


#    - restore_cache:  # ensure this step occurs *before* installing dependencies
#        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

    - run:
        name: install dependencies
        command: |
          sudo pip install pipenv
          pipenv install

#    - save_cache:
#        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#        paths:
#          - ".venv"
#          - "/usr/local/bin"
#          - "/usr/local/lib/python3.6/site-packages"

    - run:
        name: check
        command: pipenv run python manage.py check