# Generated by Django 2.2.2 on 2019-06-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_contestants', to='tourneys.Tourney')),
            ],
        ),
        migrations.CreateModel(
            name='RoundContestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('votes', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourneys.Character')),
            ],
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
    ]
