# Generated by Django 2.2.2 on 2019-06-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0005_auto_20190618_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='round_contestant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tourneys.RoundContestant'),
        ),
    ]
