# Generated by Django 2.2.2 on 2019-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0006_auto_20190618_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
