# Generated by Django 2.2.2 on 2019-06-18 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0007_match_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='match_duration',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tourney',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
