# Generated by Django 2.2.2 on 2019-06-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0008_auto_20190618_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='character1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character1', to='tourneys.Character'),
        ),
        migrations.AddField(
            model_name='match',
            name='character2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character2', to='tourneys.Character'),
        ),
        migrations.AddField(
            model_name='match',
            name='dad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child2', to='tourneys.Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='mom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child1', to='tourneys.Match'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='tourney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourneys.Tourney'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourneys.Character'),
        ),
        migrations.AddField(
            model_name='vote',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourneys.Character'),
        ),
    ]
