# Generated by Django 2.2.2 on 2019-06-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0009_auto_20190620_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='contestant1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='contestant2',
        ),
    ]
