# Generated by Django 2.2.2 on 2019-06-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0010_auto_20190620_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='round_contestant',
        ),
        migrations.DeleteModel(
            name='RoundContestant',
        ),
    ]
