# Generated by Django 2.2.2 on 2019-06-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0011_auto_20190620_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tourneys.Match'),
        ),
    ]
