# Generated by Django 2.2.2 on 2019-07-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourneys', '0012_auto_20190621_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
